"""Phase 14 (build deliverables) integration tests — deterministic, no LLM.

Seeds the full precondition graph plus generated source/test files in the
workspace, then runs ONLY phase 14 through the production flow and asserts:

  * ``deliverables.zip`` is produced with the documented structure —
    README, the seven rendered docs, and copies of source + test files
  * rendered docs actually carry the graph content (requirement IDs)
  * a re-run is deterministic (identical archive member list)
  * an empty workspace + empty graph still completes with a well-formed,
    minimal bundle (the design doc specifies deterministic packaging with
    no failure path — "given the same graph state, it always produces
    identical output")
"""

from __future__ import annotations

import zipfile
from pathlib import Path
from typing import Any

import pytest

from backend.config.models import ForgeConfig
from backend.forge_builder import ForgeBuilder
from backend.graph.models import GraphNode, LifecycleState, NodeType

pytestmark = [pytest.mark.integration, pytest.mark.asyncio, pytest.mark.timeout(900)]

SOURCE_FILE = "src/arithmetic.py"
TEST_FILE = "tests/test_arithmetic.py"

SOURCE_CONTENT = '''"""Arithmetic module (as generated by phase 12)."""
from tracing import traces


@traces("LLR-0001")
def add(a: float, b: float) -> float:
    return a + b
'''

TEST_CONTENT = '''"""Tests for the arithmetic module."""
from tracing import traces

from src.arithmetic import add


@traces("LLR-0001", case="CASE_LLR-0001")
def test_add_returns_sum() -> None:
    assert add(2, 3) == 5
'''

DOC_NAMES = (
    "01-Requirements-Specification.md",
    "02-Architecture.md",
    "03-Interface-Specification.md",
    "04-Design-Specification.md",
    "05-Test-Plan.md",
    "06-Traceability-Matrix.md",
    "07-Coverage-Report.md",
)


# ── Seeding ──────────────────────────────────────────────────────────────────


async def _seed_graph(graph: Any) -> None:
    """Seed the full graph phases 0-13 leave behind, including CODE/TEST."""
    nodes = [
        GraphNode(
            node_id="PROJECT-0001",
            node_type=NodeType.PROJECT,
            title="Adder",
            content="Tiny arithmetic project for phase-14 integration testing.",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="DOCUMENT-0001",
            node_type=NodeType.DOCUMENT,
            title="Adder Spec",
            content="Specification.",
            parent_id="PROJECT-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="PARA-0001",
            node_type=NodeType.PARA,
            title="Requirements",
            content="Requirements paragraph.",
            parent_id="DOCUMENT-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="HLR-0001",
            node_type=NodeType.HLR,
            title="Basic Arithmetic",
            content="The module SHALL support addition of two numbers.",
            parent_id="PARA-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="LLR-0001",
            node_type=NodeType.LLR,
            title="Addition",
            content="add(a, b) returns a + b.",
            parent_id="HLR-0001",
            trace_to=["HLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="ARCHITECTURE-0001",
            node_type=NodeType.ARCHITECTURE,
            title="Adder Architecture",
            content="Single-module architecture.",
            parent_id="PROJECT-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="MODULE-0001",
            node_type=NodeType.MODULE,
            title="Arithmetic",
            content="Arithmetic module.",
            parent_id="ARCHITECTURE-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="CONTRACT-0001",
            node_type=NodeType.CONTRACT,
            title="Arithmetic API",
            content="def add(a: float, b: float) -> float: ...",
            parent_id="MODULE-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="DESIGN-0001",
            node_type=NodeType.DESIGN,
            title="Arithmetic Implementation",
            content="Implement add() in src/arithmetic.py.",
            parent_id="MODULE-0001",
            trace_to=["LLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
            properties={"file_path": SOURCE_FILE},
        ),
        GraphNode(
            node_id="CODE-0001",
            node_type=NodeType.CODE,
            title="Arithmetic Implementation implementation",
            content=f"Source implementation ({SOURCE_FILE}).",
            parent_id="DESIGN-0001",
            trace_to=["LLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
            properties={"file_path": SOURCE_FILE, "file_content": SOURCE_CONTENT},
        ),
        GraphNode(
            node_id="SUITE-0001",
            node_type=NodeType.SUITE,
            title="Arithmetic Tests",
            content="Test suite.",
            parent_id="PROJECT-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="CASE_LLR-0001",
            node_type=NodeType.CASE_LLR,
            title="Test Addition",
            content="Verify add(2, 3) == 5. Traces to LLR-0001.",
            parent_id="SUITE-0001",
            trace_to=["LLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
            properties={"file_path": TEST_FILE},
        ),
        GraphNode(
            node_id="TEST-0001",
            node_type=NodeType.TEST,
            title="Test Addition tests",
            content=f"Workspace tests ({TEST_FILE}).",
            parent_id="CASE_LLR-0001",
            trace_to=["CASE_LLR-0001", "LLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
            properties={"file_path": TEST_FILE, "file_content": TEST_CONTENT},
        ),
    ]
    for node in nodes:
        await graph.add_node(node)


async def _build_flow(
    integration_config: ForgeConfig, root: Path, *, name: str
) -> Any:
    workspace = root / "workspace"
    workspace.mkdir()
    config = integration_config.model_copy(deep=True)
    config.project.workspace_dir = str(workspace)
    config.project.name = name
    builder = ForgeBuilder(config=config, workspace=workspace, db_path=root / "forge.db")
    return await builder.build()


def _namelist(zip_path: Path) -> list[str]:
    assert zip_path.exists(), f"phase 14 produced no archive at {zip_path}"
    with zipfile.ZipFile(zip_path) as zf:
        assert zf.testzip() is None, "deliverables archive is corrupt"
        return zf.namelist()


def _read_member(zip_path: Path, name: str) -> str:
    with zipfile.ZipFile(zip_path) as zf:
        return zf.read(name).decode("utf-8")


def _status(flow: Any, phase: int) -> str:
    row = flow.phase_store.get(phase)
    assert row is not None, f"phase {phase} missing from the phase store"
    return str(row["status"])


# ── Happy path ───────────────────────────────────────────────────────────────


async def test_deliverables_zip_contains_source_and_rendered_docs(
    integration_config: ForgeConfig, tmp_path: Path
) -> None:
    flow = await _build_flow(integration_config, tmp_path, name="p14-happy")
    await _seed_graph(flow.graph)
    workspace = flow._workspace
    (workspace / SOURCE_FILE).write_text(SOURCE_CONTENT, encoding="utf-8")
    (workspace / TEST_FILE).write_text(TEST_CONTENT, encoding="utf-8")

    await flow.run_phase(14)

    assert _status(flow, 14) == "complete"
    names = _namelist(workspace / "deliverables.zip")

    assert "deliverables/README.md" in names, f"no README in bundle: {names[:15]}"
    for doc in DOC_NAMES:
        assert f"deliverables/docs/{doc}" in names, f"missing rendered doc: {doc}"
    assert f"deliverables/{SOURCE_FILE}" in names, "source file not bundled"
    assert f"deliverables/{TEST_FILE}" in names, "test file not bundled"

    # The bundled source must be the workspace file, byte for byte.
    bundled = _read_member(workspace / "deliverables.zip", f"deliverables/{SOURCE_FILE}")
    assert bundled == SOURCE_CONTENT


async def test_rendered_docs_carry_graph_content(
    integration_config: ForgeConfig, tmp_path: Path
) -> None:
    flow = await _build_flow(integration_config, tmp_path, name="p14-docs")
    await _seed_graph(flow.graph)
    workspace = flow._workspace
    (workspace / SOURCE_FILE).write_text(SOURCE_CONTENT, encoding="utf-8")
    (workspace / TEST_FILE).write_text(TEST_CONTENT, encoding="utf-8")

    await flow.run_phase(14)

    zip_path = workspace / "deliverables.zip"
    reqs = _read_member(zip_path, "deliverables/docs/01-Requirements-Specification.md")
    assert "HLR-0001" in reqs, "requirements doc must list the seeded HLR"
    assert "LLR-0001" in reqs, "requirements doc must list the seeded LLR"
    matrix = _read_member(zip_path, "deliverables/docs/06-Traceability-Matrix.md")
    assert "LLR-0001" in matrix, "traceability matrix must cross-reference the LLR"


async def test_rerun_produces_identical_archive_structure(
    integration_config: ForgeConfig, tmp_path: Path
) -> None:
    """Phase 14 is documented as deterministic: same graph → same output."""
    flow = await _build_flow(integration_config, tmp_path, name="p14-rerun")
    await _seed_graph(flow.graph)
    workspace = flow._workspace
    (workspace / SOURCE_FILE).write_text(SOURCE_CONTENT, encoding="utf-8")
    (workspace / TEST_FILE).write_text(TEST_CONTENT, encoding="utf-8")

    await flow.run_phase(14)
    first = _namelist(workspace / "deliverables.zip")

    await flow.run_phase(14)
    second = _namelist(workspace / "deliverables.zip")

    assert first == second, "re-running phase 14 changed the archive member list"
    assert _status(flow, 14) == "complete"


# ── Edge: empty workspace and empty graph ────────────────────────────────────


async def test_empty_workspace_completes_with_minimal_wellformed_bundle(
    integration_config: ForgeConfig, tmp_path: Path
) -> None:
    """No graph nodes, no generated files — still a well-formed bundle.

    design/24_phase_14_build_deliverables.md specifies deterministic
    packaging with no failure path, so the phase must complete and produce
    the doc skeleton rather than raising or emitting a corrupt archive.
    """
    flow = await _build_flow(integration_config, tmp_path, name="p14-empty")
    workspace = flow._workspace

    await flow.run_phase(14)

    assert _status(flow, 14) == "complete"
    names = _namelist(workspace / "deliverables.zip")
    assert "deliverables/README.md" in names
    for doc in DOC_NAMES:
        assert f"deliverables/docs/{doc}" in names, f"missing rendered doc: {doc}"
    # Nothing was generated, so nothing beyond README + docs may be bundled.
    extras = [
        n for n in names
        if not n.startswith("deliverables/docs/") and n != "deliverables/README.md"
    ]
    assert extras == [], f"empty build bundled unexpected files: {extras}"
