"""Phase 13 (workspace sync) integration tests — deterministic, no LLM.

Seeds the full precondition graph (PROJECT through DESIGN/SUITE/CASE, with
``file_path`` properties as phase 12 leaves them) plus real generated files
on disk, then runs ONLY phase 13 through the production flow and asserts:

  * CODE/TEST child nodes are created with content hashes and trace links
  * a DESIGN whose declared file is missing surfaces loudly — a MISSING_CODE
    sync gap plus an UNSYNCED_DESIGN structural gap — instead of failing
    silently or claiming completion
  * a re-run over unchanged content is a no-op (hash and version stable)
  * a changed file is refreshed in place, not duplicated
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

import pytest

from backend.analysis.gap_analyser import GapAnalyser
from backend.analysis.gaps import GapType
from backend.config.models import ForgeConfig
from backend.forge_builder import ForgeBuilder
from backend.graph.models import GraphNode, LifecycleState, NodeType

pytestmark = [pytest.mark.integration, pytest.mark.asyncio, pytest.mark.timeout(900)]

SOURCE_FILE = "src/arithmetic.py"
TEST_FILE = "tests/test_arithmetic.py"

SOURCE_CONTENT = '''"""Arithmetic module (as generated by phase 12)."""
from tracing import traces


@traces("LLR-0001")
def add(a: float, b: float) -> float:
    return a + b
'''

TEST_CONTENT = '''"""Tests for the arithmetic module (as generated by phase 12)."""
from tracing import traces

from src.arithmetic import add


@traces("LLR-0001", case="CASE_LLR-0001")
def test_add_returns_sum() -> None:
    assert add(2, 3) == 5
'''


def _sha256(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


# ── Seeding ──────────────────────────────────────────────────────────────────


async def _seed_graph(graph: Any, *, design_file: str, case_file: str) -> None:
    """Seed PROJECT → … → DESIGN/SUITE/CASE exactly as phases 0-12 leave them.

    ``file_path`` properties are what phase 12 stamps on DESIGN and CASE
    nodes; phase 13 keys its whole scan on them.
    """
    nodes = [
        GraphNode(
            node_id="PROJECT-0001",
            node_type=NodeType.PROJECT,
            title="Adder",
            content="Tiny arithmetic project.",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="DOCUMENT-0001",
            node_type=NodeType.DOCUMENT,
            title="Adder Spec",
            content="Specification.",
            parent_id="PROJECT-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="PARA-0001",
            node_type=NodeType.PARA,
            title="Requirements",
            content="Requirements paragraph.",
            parent_id="DOCUMENT-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="HLR-0001",
            node_type=NodeType.HLR,
            title="Basic Arithmetic",
            content="The module SHALL support addition of two numbers.",
            parent_id="PARA-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="LLR-0001",
            node_type=NodeType.LLR,
            title="Addition",
            content="add(a, b) returns a + b.",
            parent_id="HLR-0001",
            trace_to=["HLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="ARCHITECTURE-0001",
            node_type=NodeType.ARCHITECTURE,
            title="Adder Architecture",
            content="Single-module architecture.",
            parent_id="PROJECT-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="MODULE-0001",
            node_type=NodeType.MODULE,
            title="Arithmetic",
            content="Arithmetic module.",
            parent_id="ARCHITECTURE-0001",
            trace_to=["HLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="CONTRACT-0001",
            node_type=NodeType.CONTRACT,
            title="Arithmetic API",
            content="def add(a: float, b: float) -> float: ...",
            parent_id="MODULE-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="DESIGN-0001",
            node_type=NodeType.DESIGN,
            title="Arithmetic Implementation",
            content="Implement add() in src/arithmetic.py.",
            parent_id="MODULE-0001",
            trace_to=["LLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
            properties={"file_path": design_file},
        ),
        GraphNode(
            node_id="SUITE-0001",
            node_type=NodeType.SUITE,
            title="Arithmetic Tests",
            content="Test suite.",
            parent_id="PROJECT-0001",
            lifecycle=LifecycleState.ACTIVE,
        ),
        GraphNode(
            node_id="CASE_LLR-0001",
            node_type=NodeType.CASE_LLR,
            title="Test Addition",
            content="Verify add(2, 3) == 5. Traces to LLR-0001.",
            parent_id="SUITE-0001",
            trace_to=["LLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
            properties={"file_path": case_file},
        ),
        # The phase-13 audit is cumulative (phase 10 must be clean too), so
        # the HLR needs an HLR-level case; it shares the same test file.
        GraphNode(
            node_id="CASE_HLR-0001",
            node_type=NodeType.CASE_HLR,
            title="Test Basic Arithmetic",
            content="Verify the arithmetic behaviour end to end. Traces to HLR-0001.",
            parent_id="SUITE-0001",
            trace_to=["HLR-0001"],
            lifecycle=LifecycleState.ACTIVE,
            properties={"file_path": case_file},
        ),
    ]
    for node in nodes:
        await graph.add_node(node)


async def _build_flow(
    integration_config: ForgeConfig, root: Path, *, name: str
) -> Any:
    workspace = root / "workspace"
    workspace.mkdir()
    config = integration_config.model_copy(deep=True)
    config.project.workspace_dir = str(workspace)
    config.project.name = name
    builder = ForgeBuilder(config=config, workspace=workspace, db_path=root / "forge.db")
    return await builder.build()


def _children_of_type(graph: Any, parent_id: str, node_type: str) -> list[Any]:
    return [c for c in graph.children_sync(parent_id) if c.node_type == node_type]


def _status(flow: Any, phase: int) -> str:
    row = flow.phase_store.get(phase)
    assert row is not None, f"phase {phase} missing from the phase store"
    return str(row["status"])


# ── Happy path ───────────────────────────────────────────────────────────────


async def test_sync_creates_code_and_test_nodes_with_hashes(
    integration_config: ForgeConfig, tmp_path: Path
) -> None:
    flow = await _build_flow(integration_config, tmp_path, name="p13-happy")
    await _seed_graph(flow.graph, design_file=SOURCE_FILE, case_file=TEST_FILE)
    workspace = flow._workspace
    (workspace / SOURCE_FILE).write_text(SOURCE_CONTENT, encoding="utf-8")
    (workspace / TEST_FILE).write_text(TEST_CONTENT, encoding="utf-8")

    await flow.run_phase(13)

    code_nodes = _children_of_type(flow.graph, "DESIGN-0001", NodeType.CODE.value)
    assert len(code_nodes) == 1, f"expected exactly 1 CODE child, got {len(code_nodes)}"
    code = code_nodes[0]
    assert code.properties["file_path"] == SOURCE_FILE
    assert code.properties["file_content"] == SOURCE_CONTENT
    assert code.properties["file_hash"] == _sha256(SOURCE_CONTENT)
    assert code.layer == 5
    assert code.trace_to == ["LLR-0001"], "CODE must inherit its DESIGN's traces"

    test_nodes = _children_of_type(flow.graph, "CASE_LLR-0001", NodeType.TEST.value)
    assert len(test_nodes) == 1, f"expected exactly 1 TEST child, got {len(test_nodes)}"
    test = test_nodes[0]
    assert test.properties["file_path"] == TEST_FILE
    assert test.properties["file_hash"] == _sha256(TEST_CONTENT)
    assert test.properties["test_functions"] == ["test_add_returns_sum"]
    assert test.layer == 6
    assert "CASE_LLR-0001" in test.trace_to, (
        "TEST must trace to its CASE — result recording keys on this"
    )

    assert _status(flow, 13) == "complete"
    assert flow._workspace_sync_gaps == []


# ── Missing file: loud gap, not silent success ───────────────────────────────


async def test_missing_design_file_emits_gap_not_silent_failure(
    integration_config: ForgeConfig, tmp_path: Path
) -> None:
    """DESIGN declares src/arithmetic.py but the file is absent from disk.

    Phase 13 must complete without raising, must NOT create a CODE node,
    must attach a MISSING_CODE sync gap, and the gap analyser must report
    the DESIGN as UNSYNCED_DESIGN — and the phase must not claim complete.
    """
    flow = await _build_flow(integration_config, tmp_path, name="p13-missing")
    await _seed_graph(flow.graph, design_file=SOURCE_FILE, case_file=TEST_FILE)
    workspace = flow._workspace
    # Only the test file exists; the declared source file is missing.
    (workspace / TEST_FILE).write_text(TEST_CONTENT, encoding="utf-8")

    await flow.run_phase(13)

    assert _children_of_type(flow.graph, "DESIGN-0001", NodeType.CODE.value) == [], (
        "no CODE node may be invented for a missing file"
    )

    sync_gaps = flow._workspace_sync_gaps
    assert len(sync_gaps) == 1, f"expected exactly 1 sync gap, got {sync_gaps}"
    assert sync_gaps[0].type == GapType.MISSING_CODE
    assert sync_gaps[0].node_id == "DESIGN-0001"
    assert sync_gaps[0].context["file_path"] == SOURCE_FILE

    analyser_gaps = GapAnalyser().analyse(flow.graph)
    unsynced = [g for g in analyser_gaps if g.type == GapType.UNSYNCED_DESIGN]
    assert [g.node_id for g in unsynced] == ["DESIGN-0001"], (
        f"gap analyser must flag DESIGN-0001 as UNSYNCED_DESIGN, got {unsynced}"
    )

    assert _status(flow, 13) != "complete", (
        "phase 13 must not report complete while a DESIGN remains unsynced"
    )


# ── Idempotency ──────────────────────────────────────────────────────────────


async def test_rerun_with_unchanged_content_is_a_noop(
    integration_config: ForgeConfig, tmp_path: Path
) -> None:
    flow = await _build_flow(integration_config, tmp_path, name="p13-rerun")
    await _seed_graph(flow.graph, design_file=SOURCE_FILE, case_file=TEST_FILE)
    workspace = flow._workspace
    (workspace / SOURCE_FILE).write_text(SOURCE_CONTENT, encoding="utf-8")
    (workspace / TEST_FILE).write_text(TEST_CONTENT, encoding="utf-8")

    await flow.run_phase(13)
    first_code = _children_of_type(flow.graph, "DESIGN-0001", NodeType.CODE.value)[0]
    first_test = _children_of_type(flow.graph, "CASE_LLR-0001", NodeType.TEST.value)[0]

    await flow.run_phase(13)

    code_nodes = _children_of_type(flow.graph, "DESIGN-0001", NodeType.CODE.value)
    test_nodes = _children_of_type(flow.graph, "CASE_LLR-0001", NodeType.TEST.value)
    assert len(code_nodes) == 1, "re-run must update in place, never duplicate"
    assert len(test_nodes) == 1, "re-run must update in place, never duplicate"

    code = code_nodes[0]
    assert code.node_id == first_code.node_id, "CODE node identity must be stable"
    assert code.properties["file_hash"] == _sha256(SOURCE_CONTENT), "hash must be stable"
    assert code.version == first_code.version, (
        "unchanged content must not bump the node version — the re-run was not a no-op"
    )
    test = test_nodes[0]
    assert test.node_id == first_test.node_id
    assert test.version == first_test.version


async def test_changed_file_is_refreshed_in_place(
    integration_config: ForgeConfig, tmp_path: Path
) -> None:
    flow = await _build_flow(integration_config, tmp_path, name="p13-refresh")
    await _seed_graph(flow.graph, design_file=SOURCE_FILE, case_file=TEST_FILE)
    workspace = flow._workspace
    (workspace / SOURCE_FILE).write_text(SOURCE_CONTENT, encoding="utf-8")
    (workspace / TEST_FILE).write_text(TEST_CONTENT, encoding="utf-8")
    await flow.run_phase(13)

    changed = SOURCE_CONTENT + "\n# regenerated\n"
    (workspace / SOURCE_FILE).write_text(changed, encoding="utf-8")

    await flow.run_phase(13)

    code_nodes = _children_of_type(flow.graph, "DESIGN-0001", NodeType.CODE.value)
    assert len(code_nodes) == 1, "refresh must not create a second CODE node"
    assert code_nodes[0].properties["file_content"] == changed
    assert code_nodes[0].properties["file_hash"] == _sha256(changed)
