"""Integration test — build and run a realistic generated workspace with bazel.

Creates a minimal but realistic workspace that mirrors Phase 12 output:
- src/calculator.py with @traces decorators (public + private functions)
- tests/test_calculator.py with @traces(case=...) decorators
- tracing/ package with the @traces decorator
- Bazel BUILD files generated by bazel_gen

Then runs `bazel test //tests/...` and verifies:
1. Bazel can build the workspace
2. Tests pass
3. Trace parser detects all @traces decorators
4. Gap finder reports zero gaps
5. Syntax errors detected and surfaced correctly
6. Untraced functions detected
7. find_gaps produces correct gap types end-to-end
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import TYPE_CHECKING, cast

import pytest

from backend.crew.bazel_gen import init_bazel_workspace
from backend.crew.gap_finder import GapKind, find_gaps
from backend.crew.trace_parser import analyse_traces
from backend.crew.workspace_scanner import scan_files
from backend.graph.models import GraphNode

if TYPE_CHECKING:
    from backend.graph.engine import ProjectGraph


def _has_bazel() -> bool:
    """Return True if bazel is runnable.

    Evaluated at import time by the skipif below, so it must swallow
    FileNotFoundError rather than let it escape and break collection.
    """
    try:
        return subprocess.run(["bazel", "version"], capture_output=True, timeout=30).returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return False


# ── Sample source code ────────────────────────────────────────────────────────

_SRC_CALCULATOR = '''\
"""Calculator module — implements basic arithmetic with validation."""

from __future__ import annotations

from dataclasses import dataclass
from tracing import traces


@dataclass
class CalcResult:
    """Result of a calculation."""
    value: float
    operation: str
    valid: bool = True
    error: str = ""


class Calculator:
    """Simple calculator with traced operations."""

    @traces("LLR-0001")
    def add(self, a: float, b: float) -> CalcResult:
        """Add two numbers."""
        return CalcResult(value=a + b, operation="add")

    @traces("LLR-0001")
    def subtract(self, a: float, b: float) -> CalcResult:
        """Subtract b from a."""
        return CalcResult(value=a - b, operation="subtract")

    @traces("LLR-0002")
    def divide(self, a: float, b: float) -> CalcResult:
        """Divide a by b with validation."""
        if not self._is_valid_divisor(b):
            return CalcResult(value=0, operation="divide", valid=False,
                              error="division by zero")
        return CalcResult(value=a / b, operation="divide")

    @traces("LLR-0002")
    def _is_valid_divisor(self, b: float) -> bool:
        """Check if b is a valid divisor — supports divide()."""
        return b != 0.0

    @traces("LLR-0001", "LLR-0002")
    def _format_result(self, result: CalcResult) -> str:
        """Format result for display — general helper."""
        if not result.valid:
            return f"Error: {result.error}"
        return f"{result.operation}: {result.value}"
'''

_TEST_CALCULATOR = '''\
"""Tests for calculator module — verifies LLR-0001 and LLR-0002."""

from src.calculator import Calculator, CalcResult
from tracing import traces


class TestAddition:
    """Tests for addition operations (LLR-0001)."""

    @traces("LLR-0001", case="CASE_LLR-0001")
    def test_add_positive_numbers(self):
        """Verify addition of positive numbers."""
        calc = Calculator()
        result = calc.add(2.0, 3.0)
        assert result.value == 5.0, f"expected 5.0, got {result.value}"
        assert result.operation == "add"

    @traces("LLR-0001", case="CASE_LLR-0001")
    def test_add_negative_numbers(self):
        """Verify addition with negative numbers."""
        calc = Calculator()
        result = calc.add(-1.0, -2.0)
        assert result.value == -3.0, f"expected -3.0, got {result.value}"

    @traces("LLR-0001", case="CASE_LLR-0001")
    def test_subtract(self):
        """Verify subtraction."""
        calc = Calculator()
        result = calc.subtract(5.0, 3.0)
        assert result.value == 2.0, f"expected 2.0, got {result.value}"


class TestDivision:
    """Tests for division operations (LLR-0002)."""

    @traces("LLR-0002", case="CASE_LLR-0002")
    def test_divide_normal(self):
        """Verify normal division."""
        calc = Calculator()
        result = calc.divide(10.0, 2.0)
        assert result.value == 5.0, f"expected 5.0, got {result.value}"
        assert result.valid is True

    @traces("LLR-0002", case="CASE_LLR-0002")
    def test_divide_by_zero(self):
        """Verify division by zero returns error."""
        calc = Calculator()
        result = calc.divide(10.0, 0.0)
        assert result.valid is False
        assert "zero" in result.error
'''

_TRACING_INIT = '''\
"""FORGE tracing decorators — runtime-queryable requirement annotations."""

from .decorator import traces

__all__ = ["traces"]
'''

_TRACING_DECORATOR = '''\
"""Requirement traceability decorator."""

from __future__ import annotations
from typing import TypeVar, Callable

_F = TypeVar("_F", bound=Callable)


def traces(*llr_ids: str, case: str | list[str] | None = None) -> Callable[[_F], _F]:
    """Annotate a function with requirement trace IDs."""
    if case is None:
        case_list: list[str] = []
    elif isinstance(case, str):
        case_list = [case]
    else:
        case_list = list(case)

    def decorator(obj: _F) -> _F:
        obj._trace_llrs = list(llr_ids)
        obj._trace_cases = case_list
        return obj

    return decorator
'''


# ── Workspace builder ─────────────────────────────────────────────────────────

def _build_workspace(ws: Path) -> None:
    """Create a complete, buildable workspace."""
    # Source
    src = ws / "src"
    src.mkdir()
    (src / "__init__.py").write_text("")
    (src / "calculator.py").write_text(_SRC_CALCULATOR)

    # Tests
    tests = ws / "tests"
    tests.mkdir()
    (tests / "__init__.py").write_text("")
    (tests / "test_calculator.py").write_text(_TEST_CALCULATOR)

    # Tracing package
    tracing = ws / "tracing"
    tracing.mkdir()
    (tracing / "__init__.py").write_text(_TRACING_INIT)
    (tracing / "decorator.py").write_text(_TRACING_DECORATOR)

    # Bazel workspace (MODULE.bazel, BUILD files, etc)
    init_bazel_workspace(ws)


# ── Graph stub ────────────────────────────────────────────────────────────────


class _StubGraph:
    """Minimal stand-in for ProjectGraph — only implements all_nodes().

    Mirrors the calculator workspace: one DESIGN (→ src/calculator.py),
    two LLRs, and two CASE_LLR nodes (→ tests/test_calculator.py).
    """

    def __init__(self, nodes: list[GraphNode] | None = None) -> None:
        self._nodes = nodes if nodes is not None else _default_graph_nodes()

    def all_nodes(self) -> list[GraphNode]:
        return list(self._nodes)


def _stub_graph() -> ProjectGraph:
    """Return a `_StubGraph` typed as `ProjectGraph`.

    ``find_gaps`` only calls ``all_nodes()`` on the graph it is given, so the
    stub is substitutable at runtime; the cast records that for the checker.
    """
    return cast("ProjectGraph", _StubGraph())


def _default_graph_nodes() -> list[GraphNode]:
    """Graph nodes that match the calculator workspace layout."""
    return [
        GraphNode(
            node_id="DESIGN-calc",
            node_type="DESIGN",
            title="Calculator",
        ),
        GraphNode(node_id="LLR-0001", node_type="LLR", title="Arithmetic"),
        GraphNode(node_id="LLR-0002", node_type="LLR", title="Division"),
        GraphNode(
            node_id="CASE_LLR-0001",
            node_type="CASE_LLR",
            title="Calculator",
        ),
        GraphNode(
            node_id="CASE_LLR-0002",
            node_type="CASE_LLR",
            title="Calculator",
        ),
    ]


# ── Tests ─────────────────────────────────────────────────────────────────────


def test_workspace_structure(tmp_path: Path) -> None:
    """Verify all expected files are created."""
    _build_workspace(tmp_path)

    assert (tmp_path / "MODULE.bazel").exists()
    assert (tmp_path / ".bazelrc").exists()
    assert (tmp_path / "BUILD.bazel").exists()
    assert (tmp_path / "src" / "BUILD.bazel").exists()
    assert (tmp_path / "tests" / "BUILD.bazel").exists()
    assert (tmp_path / "tracing" / "BUILD.bazel").exists()
    assert (tmp_path / "src" / "calculator.py").exists()
    assert (tmp_path / "tests" / "test_calculator.py").exists()


def test_src_build_deps_include_tracing(tmp_path: Path) -> None:
    """src/BUILD.bazel should depend on //tracing."""
    _build_workspace(tmp_path)
    text = (tmp_path / "src" / "BUILD.bazel").read_text()
    assert "//tracing" in text


def test_tests_build_deps_include_tracing(tmp_path: Path) -> None:
    """tests/BUILD.bazel should depend on //tracing."""
    _build_workspace(tmp_path)
    text = (tmp_path / "tests" / "BUILD.bazel").read_text()
    assert "//tracing" in text
    assert "//src" in text


def test_trace_parser_detects_all_traces(tmp_path: Path) -> None:
    """Trace parser should detect @traces on all functions (public + private)."""
    _build_workspace(tmp_path)

    code = (tmp_path / "src" / "calculator.py").read_text()
    analysis = analyse_traces(code)

    # 5 functions total: add, subtract, divide, _is_valid_divisor, _format_result
    assert analysis.total_functions == 5
    assert analysis.traced_functions == 5
    assert len(analysis.untraced) == 0

    # Check specific traces
    symbols = {t.symbol: t.llr_ids for t in analysis.traces}
    assert symbols["add"] == ["LLR-0001"]
    assert symbols["divide"] == ["LLR-0002"]
    assert symbols["_is_valid_divisor"] == ["LLR-0002"]
    assert symbols["_format_result"] == ["LLR-0001", "LLR-0002"]


def test_trace_parser_detects_test_traces(tmp_path: Path) -> None:
    """Trace parser should detect @traces with case= on test functions."""
    _build_workspace(tmp_path)

    code = (tmp_path / "tests" / "test_calculator.py").read_text()
    analysis = analyse_traces(code)

    assert analysis.total_functions == 5
    assert analysis.traced_functions == 5

    # Check CASE IDs
    case_traces = {t.symbol: t.case_ids for t in analysis.traces if t.case_ids}
    assert case_traces["test_add_positive_numbers"] == ["CASE_LLR-0001"]
    assert case_traces["test_divide_by_zero"] == ["CASE_LLR-0002"]


def test_gap_finder_reports_zero_gaps(tmp_path: Path) -> None:
    """Fully traced workspace should have zero UNTRACED_FUNCTIONS gaps."""
    _build_workspace(tmp_path)

    source_files, test_files = scan_files(tmp_path)

    # All functions should be traced
    for path, fs in source_files.items():
        assert len(fs.untraced_functions) == 0, (
            f"{path} has untraced functions: "
            f"{[u.name for u in fs.untraced_functions]}"
        )
    for path, fs in test_files.items():
        assert len(fs.untraced_functions) == 0, (
            f"{path} has untraced functions: "
            f"{[u.name for u in fs.untraced_functions]}"
        )


def test_syntax_error_detected_in_source(tmp_path: Path) -> None:
    """scan_files should detect a syntax error in a source file."""
    _build_workspace(tmp_path)

    # Inject a syntax error into calculator source
    calc = tmp_path / "src" / "calculator.py"
    calc.write_text(_SRC_CALCULATOR + "\ndef broken(\n")

    source_files, _test_files = scan_files(tmp_path)

    fs = source_files["src/calculator.py"]
    assert fs.syntax_error, "expected syntax error to be detected"
    # Verify the error references the injected code, not just any "(line N)"
    assert "broken" in fs.syntax_error, (
        f"error should mention 'broken': {fs.syntax_error}"
    )


def test_syntax_error_detected_in_test(tmp_path: Path) -> None:
    """scan_files should detect a syntax error in a test file."""
    _build_workspace(tmp_path)

    # Overwrite test file with broken syntax
    test_file = tmp_path / "tests" / "test_calculator.py"
    test_file.write_text("def test_broken(\n    pass\n")

    _source_files, test_files = scan_files(tmp_path)

    fs = test_files["tests/test_calculator.py"]
    assert fs.syntax_error, "expected syntax error to be detected"
    assert "test_broken" in fs.syntax_error, (
        f"error should mention 'test_broken': {fs.syntax_error}"
    )


def test_no_syntax_error_on_valid_files(tmp_path: Path) -> None:
    """Valid workspace should have empty syntax_error on all files."""
    _build_workspace(tmp_path)

    source_files, test_files = scan_files(tmp_path)

    for path, fs in {**source_files, **test_files}.items():
        assert fs.syntax_error == "", (
            f"{path} has unexpected syntax error: {fs.syntax_error}"
        )


def test_syntax_error_isolated_to_broken_file(tmp_path: Path) -> None:
    """Only the broken file should have a syntax_error; others stay clean."""
    _build_workspace(tmp_path)

    # Add a second source file with a syntax error
    (tmp_path / "src" / "broken_module.py").write_text(
        "class Oops:\n    def bad(self\n"
    )

    source_files, test_files = scan_files(tmp_path)

    # broken_module has an error
    assert source_files["src/broken_module.py"].syntax_error

    # calculator is still fine
    assert source_files["src/calculator.py"].syntax_error == ""

    # test files are still fine
    for path, fs in test_files.items():
        assert fs.syntax_error == "", f"{path} unexpectedly has syntax error"


# ── Untraced function detection ───────────────────────────────────────────────


def test_untraced_source_function_detected(tmp_path: Path) -> None:
    """Adding a function without @traces should appear in untraced_functions."""
    _build_workspace(tmp_path)

    calc = tmp_path / "src" / "calculator.py"
    calc.write_text(
        _SRC_CALCULATOR + "\n\ndef untraced_helper(x):\n    return x + 1\n"
    )

    source_files, _test_files = scan_files(tmp_path)

    fs = source_files["src/calculator.py"]
    names = [uf.name for uf in fs.untraced_functions]
    assert "untraced_helper" in names


def test_untraced_test_function_detected(tmp_path: Path) -> None:
    """A test function without @traces should appear in untraced_functions."""
    _build_workspace(tmp_path)

    test_file = tmp_path / "tests" / "test_calculator.py"
    test_file.write_text(
        _TEST_CALCULATOR + "\n\ndef test_no_trace():\n    assert True\n"
    )

    _source_files, test_files = scan_files(tmp_path)

    fs = test_files["tests/test_calculator.py"]
    names = [uf.name for uf in fs.untraced_functions]
    assert "test_no_trace" in names


# ── Gap finder end-to-end ────────────────────────────────────────────────────


def test_find_gaps_zero_on_clean_workspace(tmp_path: Path) -> None:
    """find_gaps should return no file-level gaps for a fully-traced workspace.

    UNCOVERED_REQUIREMENT gaps are expected because we pass no test results
    (no bazel run).  Everything else — syntax, missing files, traces — should
    be clean.
    """
    _build_workspace(tmp_path)

    source_files, test_files = scan_files(tmp_path)
    graph = _stub_graph()

    gaps = find_gaps(source_files, test_files, [], graph)

    non_req_gaps = [g for g in gaps if g.kind != GapKind.UNCOVERED_REQUIREMENT]
    assert non_req_gaps == [], f"expected 0 non-requirement gaps, got: {non_req_gaps}"

    # Verify graph IS wired: exactly 2 UNCOVERED_REQUIREMENT (one per LLR)
    req_gaps = [g for g in gaps if g.kind == GapKind.UNCOVERED_REQUIREMENT]
    assert len(req_gaps) == 2, f"expected 2 UNCOVERED_REQUIREMENT gaps, got {len(req_gaps)}"
    req_ids = {g.node_id for g in req_gaps}
    assert req_ids == {"LLR-0001", "LLR-0002"}


def test_find_gaps_syntax_error_gap(tmp_path: Path) -> None:
    """A syntax error in src/ should produce a SYNTAX_ERROR gap."""
    _build_workspace(tmp_path)

    calc = tmp_path / "src" / "calculator.py"
    calc.write_text(_SRC_CALCULATOR + "\ndef broken(\n")

    source_files, test_files = scan_files(tmp_path)
    graph = _stub_graph()

    gaps = find_gaps(source_files, test_files, [], graph)

    syntax_gaps = [g for g in gaps if g.kind == GapKind.SYNTAX_ERROR]
    assert len(syntax_gaps) == 1
    assert syntax_gaps[0].file_path == "src/calculator.py"


def test_find_gaps_untraced_functions_gap(tmp_path: Path) -> None:
    """An untraced function should produce an UNTRACED_FUNCTIONS gap."""
    _build_workspace(tmp_path)

    calc = tmp_path / "src" / "calculator.py"
    calc.write_text(
        _SRC_CALCULATOR + "\n\ndef orphan():\n    return 42\n"
    )

    source_files, test_files = scan_files(tmp_path)
    graph = _stub_graph()

    gaps = find_gaps(source_files, test_files, [], graph)

    untraced_gaps = [g for g in gaps if g.kind == GapKind.UNTRACED_FUNCTIONS]
    assert len(untraced_gaps) == 1, (
        f"expected exactly 1 UNTRACED_FUNCTIONS gap, got {len(untraced_gaps)}"
    )
    assert untraced_gaps[0].file_path == "src/calculator.py"
    assert "orphan" in untraced_gaps[0].details


def test_find_gaps_syntax_error_is_highest_file_priority(tmp_path: Path) -> None:
    """SYNTAX_ERROR gaps should sort before UNTRACED_FUNCTIONS gaps.

    The syntax error is in src/calculator.py (replaced entirely with broken
    code, so it has 0 parsed functions).  The untraced function is
    test_no_trace in tests/test_calculator.py (valid syntax, no @traces).
    """
    _build_workspace(tmp_path)

    # Source with syntax error — replaces entire file
    calc = tmp_path / "src" / "calculator.py"
    calc.write_text("def broken(\n")

    # Test with an untraced function (valid syntax)
    test_file = tmp_path / "tests" / "test_calculator.py"
    test_file.write_text(
        _TEST_CALCULATOR + "\n\ndef test_no_trace():\n    assert True\n"
    )

    source_files, test_files = scan_files(tmp_path)
    graph = _stub_graph()

    gaps = find_gaps(source_files, test_files, [], graph)

    # Verify both gap types are present and from the expected files
    syntax_gaps = [g for g in gaps if g.kind == GapKind.SYNTAX_ERROR]
    untraced_gaps = [g for g in gaps if g.kind == GapKind.UNTRACED_FUNCTIONS]
    assert len(syntax_gaps) == 1
    assert syntax_gaps[0].file_path == "src/calculator.py"
    assert len(untraced_gaps) == 1
    assert untraced_gaps[0].file_path == "tests/test_calculator.py"

    # SYNTAX_ERROR (priority 1) must sort before UNTRACED_FUNCTIONS (6)
    kinds = [g.kind for g in gaps]
    assert kinds.index(GapKind.SYNTAX_ERROR) < kinds.index(GapKind.UNTRACED_FUNCTIONS)


def test_find_gaps_invalid_traces_gap(tmp_path: Path) -> None:
    """@traces referencing a non-existent LLR should produce INVALID_TRACES."""
    _build_workspace(tmp_path)

    # Add source with a bogus LLR ID
    (tmp_path / "src" / "bogus.py").write_text(
        "from tracing import traces\n\n"
        '@traces("LLR-9999")\n'
        "def bogus_func():\n"
        "    pass\n"
    )

    source_files, test_files = scan_files(tmp_path)
    graph = _stub_graph()

    gaps = find_gaps(source_files, test_files, [], graph)

    invalid_gaps = [g for g in gaps if g.kind == GapKind.INVALID_TRACES]
    assert len(invalid_gaps) == 1, (
        f"expected exactly 1 INVALID_TRACES gap, got {len(invalid_gaps)}"
    )
    assert invalid_gaps[0].file_path == "src/bogus.py"
    assert "LLR-9999" in invalid_gaps[0].details


# ── Compound / edge cases ───────────────────────────────────────────────────


def test_syntax_error_and_untraced_coexist(tmp_path: Path) -> None:
    """Both a syntax error and untraced functions in different files."""
    _build_workspace(tmp_path)

    # Broken syntax in one file
    (tmp_path / "src" / "broken.py").write_text("if True\n    pass\n")

    # Untraced function in another file
    calc = tmp_path / "src" / "calculator.py"
    calc.write_text(
        _SRC_CALCULATOR + "\n\ndef lonely():\n    return 1\n"
    )

    source_files, test_files = scan_files(tmp_path)

    assert source_files["src/broken.py"].syntax_error
    assert source_files["src/calculator.py"].syntax_error == ""

    names = [uf.name for uf in source_files["src/calculator.py"].untraced_functions]
    assert "lonely" in names


def test_empty_py_file_no_errors(tmp_path: Path) -> None:
    """An empty .py file should not produce a syntax error or functions."""
    _build_workspace(tmp_path)

    (tmp_path / "src" / "empty_module.py").write_text("")

    source_files, _test_files = scan_files(tmp_path)

    fs = source_files["src/empty_module.py"]
    assert fs.syntax_error == ""
    assert fs.total_functions == 0
    assert len(fs.untraced_functions) == 0


def test_comments_only_file_no_errors(tmp_path: Path) -> None:
    """A file with only comments/docstrings should parse cleanly."""
    _build_workspace(tmp_path)

    (tmp_path / "src" / "docs_only.py").write_text(
        '"""Module-level docstring."""\n\n# just a comment\n'
    )

    source_files, _test_files = scan_files(tmp_path)

    fs = source_files["src/docs_only.py"]
    assert fs.syntax_error == ""
    assert fs.total_functions == 0
    assert len(fs.untraced_functions) == 0


# ── Scanner robustness ──────────────────────────────────────────────────────


def test_nested_package_scanned(tmp_path: Path) -> None:
    """scan_files should recurse into subdirectories under src/."""
    _build_workspace(tmp_path)

    utils = tmp_path / "src" / "utils"
    utils.mkdir()
    (utils / "__init__.py").write_text("")
    (utils / "helpers.py").write_text(
        "from tracing import traces\n\n"
        '@traces("LLR-0001")\n'
        "def helper():\n"
        "    return 42\n"
    )

    source_files, _test_files = scan_files(tmp_path)

    assert "src/utils/helpers.py" in source_files
    fs = source_files["src/utils/helpers.py"]
    assert fs.total_functions == 1
    assert fs.traced_functions == 1
    assert fs.syntax_error == ""


def test_conftest_and_init_excluded(tmp_path: Path) -> None:
    """__init__.py and conftest.py should not appear in scan results."""
    _build_workspace(tmp_path)

    # Add a conftest.py in tests/
    (tmp_path / "tests" / "conftest.py").write_text(
        "def pytest_configure(config):\n    pass\n"
    )

    source_files, test_files = scan_files(tmp_path)

    all_paths = set(source_files) | set(test_files)
    assert not any("__init__" in p for p in all_paths), (
        f"__init__.py should be excluded: {all_paths}"
    )
    assert not any("conftest" in p for p in all_paths), (
        f"conftest.py should be excluded: {all_paths}"
    )


# ── BUILD regeneration ──────────────────────────────────────────────────────


def test_build_regeneration_picks_up_new_files(tmp_path: Path) -> None:
    """Adding a new test file and re-running init should update BUILD."""
    _build_workspace(tmp_path)

    # Add a new test file
    (tmp_path / "tests" / "test_new_feature.py").write_text(
        "from tracing import traces\n\n"
        '@traces("LLR-0001", case="CASE_LLR-0001")\n'
        "def test_new_thing():\n"
        "    assert True\n"
    )

    # Re-init should regenerate BUILD with the new target
    init_bazel_workspace(tmp_path)

    text = (tmp_path / "tests" / "BUILD.bazel").read_text()
    assert "test_new_feature" in text
    assert "test_calculator" in text


def test_build_regen_after_syntax_error_file_added(tmp_path: Path) -> None:
    """init_bazel_workspace should still generate a valid BUILD for src/.

    src/ uses a glob, so the broken file is implicitly included.
    The BUILD itself must remain valid (not crash during generation).
    """
    _build_workspace(tmp_path)

    (tmp_path / "src" / "broken.py").write_text("def oops(\n")

    # Re-generate — should not raise
    init_bazel_workspace(tmp_path)

    text = (tmp_path / "src" / "BUILD.bazel").read_text()
    assert "py_library" in text
    assert "glob" in text


# ── Full bazel integration ──────────────────────────────────────────────────


@pytest.mark.slow
@pytest.mark.skipif(not _has_bazel(), reason="bazel not available")
def test_bazel_test_passes(tmp_path: Path) -> None:
    """Full integration: bazel test //tests/... should pass."""
    _build_workspace(tmp_path)

    result = subprocess.run(
        ["bazel", "test", "//tests/...", "--test_output=errors"],
        cwd=str(tmp_path),
        capture_output=True,
        text=True,
        timeout=120,
    )

    assert result.returncode == 0, (
        f"bazel test failed:\nSTDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
    )
